DROP TABLE IF EXISTS department;

CREATE TABLE department (
	departmentId INT8 GENERATED BY DEFAULT AS IDENTITY,
	departmentName varchar(25) UNIQUE NOT NULL,
	departmentAddress varchar(25) NOT NULL,
	departmentCode varchar(3)

);

-- insert into "department"(departmentName, departmentAddress, departmentCode )  
-- VALUES ('Finance', 'oakland', 'FIN');
-- insert into "department"(departmentName, departmentAddress, departmentCode )  
-- VALUES ('IT', 'Dallas', 'it');