DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
	id INT8 GENERATED BY DEFAULT AS IDENTITY,
	email varchar(25) UNIQUE NOT NULL,
	first_name varchar(25) NOT NULL,
	last_name varchar(25)
);

-- insert into "employee"(email, first_name, last_name )  VALUES ('skumar@everest.com', 'Shankar', 'Kumar');
-- insert into "employee"(email, first_name, last_name )  VALUES ('jpatil@everest.com', 'Jayant', 'Patil');
-- select * from "employee"

--CREATE PROCEDURE count_employees() 
--LANGUAGE SQL
--AS $$ 
--  SELECT count(*) from employee where first_name like 'S%'
--$$;
